In [1]:
import numpy as np
import os
import random
import pandas as pd
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import sklearn.datasets, sklearn.decomposition
from matplotlib.transforms import ScaledTranslation
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix


def traintestMNIST(labels=None, ntrain=None, ntest=None, path=os.path.join('data_for_python', 'mnist.npz')):
    mnist = np.load(path)
    train_x = mnist['train_x']
    train_y = mnist['train_y']
    train = np.asarray(list(zip(train_x, train_y)))

    test_x = mnist['test_x']
    test_y = mnist['test_y']
    test = np.asarray(list(zip(test_x, test_y)))

    if labels:
        train = list(train[np.hstack([np.where(train_y==l) for l in labels]).squeeze()])
        test = list(test[np.hstack([np.where(test_y==l) for l in labels]).squeeze()])

    random.shuffle(train)
    random.shuffle(test)

    train_x, train_y = zip(*train)
    test_x, test_y = zip(*test)

    if ntrain:
        train_x = train_x[:ntrain]
        train_y = train_y[:ntrain]

    if ntest:
        test_x = test_x[:ntest]
        test_y = test_y[:ntest]

    return np.asarray(train_x), np.asarray(train_y), np.asarray(test_x), np.asarray(test_y)

In [8]:
def g(n1,n2):
    [trainImages3, trainLabels3, testImages3, testLabels3] = traintestMNIST([n1,n2], 2000)
    kmeans3 = KMeans(n_clusters=2, random_state=0).fit(trainImages3)
    kmeans_est3=kmeans3.predict(testImages3)
    temp2_3=np.where(kmeans_est3==1)[0]
    kmeans_est_bis3=np.uint(np.zeros(len(kmeans_est3))+n1) #trick pr transformer les 0 en 7 et 1 en 3
    for i in temp2_3:
        kmeans_est_bis3[i]=n2
    cm3=confusion_matrix(testLabels3,kmeans_est_bis3)
    return(cm3)

In [9]:
cm_37 = []
for _ in range(50):
    cm_37.append(g(3,7))

In [13]:
print('Pour matrice de confusion:\n\n 3 vs. 7 \n ')
print('---------\nmean:\n')
print(np.mean(cm_37,0))
print('---------\nmedian:\n')
print(np.median(cm_37,0))
print('---------\nmin:\n')
print(np.amin(cm_37,0))
print('---------\nmax:\n')
print(np.amax(cm_37,0))
print('---------\nvar:\n')
print(np.var(cm_37,0))

Pour matrice de confusion:

 3 vs. 7 
 
---------
mean:

[[559.44 450.56]
 [454.98 573.02]]
---------
median:

[[ 958.   52.]
 [  26. 1002.]]
---------
min:

[[45 46]
 [22 22]]
---------
max:

[[ 964  965]
 [1006 1006]]
---------
var:

[[203957.0064 203957.0064]
 [236050.8996 236050.8996]]


In [10]:
cm_35 = []
for _ in range(50):
    cm_35.append(g(3,5))

In [14]:
print('Pour matrice de confusion:\n\n 3 vs. 5 \n ')
print('---------\nmean:\n')
print(np.mean(cm_35,0))
print('---------\nmedian:\n')
print(np.median(cm_35,0))
print('---------\nmin:\n')
print(np.amin(cm_35,0))
print('---------\nmax:\n')
print(np.amax(cm_35,0))
print('---------\nvar:\n')
print(np.var(cm_35,0))

Pour matrice de confusion:

 3 vs. 5 
 
---------
mean:

[[489.82 520.18]
 [456.28 435.72]]
---------
median:

[[352.  658. ]
 [530.5 361.5]]
---------
min:

[[213 169]
 [322 319]]
---------
max:

[[841 797]
 [573 570]]
---------
var:

[[52557.4276 52557.4276]
 [ 9559.6416  9559.6416]]
